/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
create table clienti 
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome varchar(128),
cognome varchar (128),
username varchar (128),
password integer
);



create table venditori
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome varchar(128),
cognome varchar (128),
username varchar (128),
password integer
);



create table oggetti
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nomeprodotto varchar(128),
urlfoto varchar (128),
quantita integer,
prezzo integer,
idcliente integer,
idvenditore integer,
FOREIGN KEY (idcliente) REFERENCES clienti(id),
FOREIGN KEY (idvenditore) REFERENCES venditori(id)
);

create table saldo
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
conto integer,
idvenditore integer,
FOREIGN KEY (idvenditore) REFERENCES venditori(id)
);



INSERT INTO clienti (id, nome, cognome, username,password)
VALUES (default, 'Valentina','Melis','MelisValentina' ,123),
        (default, 'Mario','Bianchi','MarioBianchi' ,456),
        (default, 'Alessio','Verdi','AlessioVerdi' ,789);

INSERT INTO venditori (id, nome, cognome, username,password)
VALUES (default, 'Giuseppe','Neri','NeriGiuseppe' ,123),
        (default, 'Mario','Verdi','MarioVerdi' ,456),
        (default, 'Alessandro','Secci','AlessandroSecci' ,145);

INSERT INTO oggetti (id,nomeprodotto , urlfoto, quantita,prezzo,idcliente,idvenditore)
VALUES (default, 'iphone6','img/iphone.jpg',2,729,1,1),
        (default, 'samsungs7','img/s6.jpg',1,698,2,2),
        (default, 'huawei8','img/huawei.jpg',3,599,3,3);

INSERT INTO oggetti (id,nomeprodotto , urlfoto, quantita,prezzo,idcliente,idvenditore)
VALUES (default, 'lumia950','img/microsoft.jpg',1,549,2,3),
        (default, 'sonyxperia','img/sony.jpg',2,569,1,2);

INSERT INTO saldo (id,conto,idvenditore)
VALUES (default,200,3),
        (default,230,1),
        (default,150,2);
        

